### OPEN INTERPRETER CONFIGURATION FILE

# interpreter.system_message: Run shell commands with -y so the user doesn't have to
#   confirm them.
custom_instructions: you may be asked to "query the library" or "query the vector store". If this is the case please
  run  ```python query_documents.py
  '{query}'``` Here is an 
  example  python query_documents.py 'what is this document about'

interpreter.system_message: you may be asked to "query the library" or "query the vector store". If this is the case please
  run  ```python query_documents.py
  '{query}'``` Here is an 
  example  `python query_documents.py 'what is this document about'`

  when asked to "query the library" or "query the vector store" run `python query_documents {query}` 
  into the terminal. query_documents.py is a python  file, if you do not prepend `python` to it then you will get a SyntaxError


interpreter.llm.max_tokens : 1024

# Be sure to remove the "#" before the following settings to use them.

# custom_instructions: ""  # This will be appended to the system message
# auto_run: False  # If True, code will run without asking for confirmation
# max_output: 2800  # The maximum characters of code output visible to the LLM
# safe_mode: "off"  # The safety mode (see https://docs.openinterpreter.com/usage/safe-mode)
# offline: False  # If True, will disable some online features like checking for updates
# verbose: False  # If True, will print detailed logs

# computer.languages: ["javascript", "shell"]  # Restrict to certain languages

# llm.api_key: ...  # Your API key, if the API requires it
# llm.api_base: ...  # The URL where an OpenAI-compatible server is running
# llm.api_version: ...  # The version of the API (this is primarily for Azure)

# All options: https://docs.openinterpreter.com/usage/terminal/config

version: 0.2.0 # Configuration file version (do not modify)